### ISSUE TITLE
Images with spaces do not load on Linux

### ISSUE THREAD

**Issue by FrankGalligan** [syoyo/tinygltf#236] opened 2020-01-13 23:04 UTC
I attached a sample glTF file that has an external reference to an image with spaces in the filename.

Below is the text for the images element in the glTF file:
"images": [
    {
      "uri": "2x2 image has spaces.png"
    }
  ],

[CubeImageUriSpaces.zip](https://github.com/syoyo/tinygltf/files/4056395/CubeImageUriSpaces.zip)

**Comment by FrankGalligan** [comment] 2020-01-13 23:19
Per this https://github.com/KhronosGroup/glTF/issues/1449 spaces are valid.

**Comment by syoyo** [comment] 2020-01-14 09:03
Thanks! PR has been merged.

FYI,  percent-encoded URI support will be soon merged: https://github.com/syoyo/tinygltf/issues/228

**Comment by AlexApps99** [comment] 2020-01-17 06:45
@syoyo @FrankGalligan 
Now this repo can't be cloned on Windows at all :(
```
error: invalid path 'models/CubeImageUriSpaces/ 2x2 image  has multiple      spaces.png '
Unable to checkout 'bcf2ce586ee8bf2a2a816afa6bfe2f8692ba6ac2' in submodule path 'lib/tinygltf'
```

**Comment by syoyo** [comment] 2020-01-17 06:53
@AlexApps99 I can git clone using Git for Windows(MinTTY) on Windows 10. what git configuration do you use?

**Comment by AlexApps99** [comment] 2020-01-17 06:56
I included it as a submodule in my engine and my CI (github actions) spat out that error cloning with https://github.com/actions/checkout

**Comment by AlexApps99** [comment] 2020-01-17 06:57
It could be a filesystem error, as CI may not use NTFS like traditional windows installations

**Comment by AlexApps99** [comment] 2020-01-17 06:59
Nevermind, the issue seems to be that the file extension ends with spaces (`.png `)

**Comment by syoyo** [comment] 2020-01-17 07:05
At least filename with whitespace should be handled well on Windows(at least AppVeyor CI build works well https://ci.appveyor.com/project/syoyo/tinygltf )

`git config core.protectNTFS false` may help. 

https://stackoverflow.com/questions/29294910/unable-to-add-files-with-name-containing-tilde-followed-by-a-number/29300360#29300360

**Comment by AlexApps99** [comment] 2020-01-17 07:06
Since the file does not have a correct png file extension, it shouldn't even be a part of the tests.
I can't change the system configuration as it is CI and resets every commit.

**Comment by AlexApps99** [comment] 2020-01-17 07:09
The problem isn't that there is whitespace, but that it is at the start and end of the filename.
I don't know how or why, but it doesn't work at all with GitHub Actions (which me and a lot of other projects use)

**Comment by syoyo** [comment] 2020-01-17 07:18
I'v deleted extra whitespace after the filename: https://github.com/syoyo/tinygltf/commit/23d1ff2880c4c98f635dcc3ec9df5ac49cb89016

Please try cloning again with recent `master`

**Comment by AlexApps99** [comment] 2020-01-17 07:23
It worked! Thank you :heart: 
```
Submodule path 'lib/tinygltf': checked out '23d1ff2880c4c98f635dcc3ec9df5ac49cb89016'
```

**Comment by FrankGalligan** [comment] 2020-01-17 16:57
Thanks @syoyo. That file I wanted to have beginning whitespace, > 1 consecutive whitespace, and a trailing whitespace. But I agree the trailing whitespace would affect the extension was was overkill on my part.

**Comment by syoyo** [comment] 2020-01-17 17:38
@FrankGalligan Thank you for the info. 

It looks git config in GitHub Actions(`core.protectNTFS=true` ?) does not allow trailing whitespaces in file extension(whitespaces in the beginning of filename was OK)

**Closed** 2020-03-11 09:49 UTC
Labels: bug
