### ISSUE TITLE
'bufferView' property is missing in Accessor error loading some sample glTF files

### ISSUE THREAD

**Issue by nyue** [syoyo/tinygltf#131] opened 2019-01-06 09:25 UTC
Hi,

  While testing out the TinyglTF loader on some reference files I found here

    https://github.com/KhronosGroup/glTF-Sample-Models

  I saw the following errors which I'd like to report

`
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/2CylinderEngine/glTF-Draco/2CylinderEngine.gltf
Err: Unknown image format.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/AntiqueCamera/glTF/AntiqueCamera.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/Avocado/glTF-Draco/Avocado.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/BarramundiFish/glTF-Draco/BarramundiFish.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/BoomBox/glTF-Draco/BoomBox.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/Box/glTF-Draco/Box.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/BrainStem/glTF-Draco/BrainStem.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/Buggy/glTF-Draco/Buggy.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/CesiumMan/glTF-Draco/CesiumMan.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/CesiumMilkTruck/glTF-Draco/CesiumMilkTruck.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/Corset/glTF-Draco/Corset.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/Duck/glTF-Draco/Duck.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/GearboxAssy/glTF-Draco/GearboxAssy.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/Lantern/glTF-Draco/Lantern.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/Monster/glTF-Draco/Monster.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/ReciprocatingSaw/glTF-Draco/ReciprocatingSaw.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/RiggedFigure/glTF-Draco/RiggedFigure.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/RiggedSimple/glTF-Draco/RiggedSimple.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/VC/glTF-Draco/VC.gltf
Err: 'bufferView' property is missing in Accessor.

Failed to parse glTF: /home/nicholas/projects/glTF/glTF-Sample-Models_git/2.0/WaterBottle/glTF-Draco/WaterBottle.gltf
`

Cheers

**Comment by syoyo** [comment] 2019-01-06 10:00
I don't get bufferView error. What version(commit) do you use?

Still I found recently added `AntiqueCamera.gltf` uses 16bit PNG, which is not supported in stb image loader, so add more expressive error report for it in this commit:

https://github.com/syoyo/tinygltf/commit/af3ebb2e76fd2bc7c4afcdf58b21d5b33590542f

Now you'll see 

```
Testing: /home/syoyo/work/glTF-Sample-Models/2.0/AntiqueCamera/glTF/AntiqueCamera.gltf
b'Reading ASCII glTF\nErr: Unknown image format. STB cannot decode image data for image[0] name = "camera_camera_Normal". Proably 16bit PNG?\n\nFailed to parse glTF\n'
b''
```

**Comment by syoyo** [comment] 2019-01-06 15:22
You can contribute Draco support to TinyGLTF. PR is always welcome!

**Comment by Ybalrid** [comment] 2019-03-06 23:27
@nyue since Drago has been merged in master at the end of January, would you mind re-testing these files? As far as I can tell, they should *just works* now...

**Comment by syoyo** [comment] 2019-03-08 05:02
I have confirmed all test passes using `loader_example` with draco support.

**Closed by syoyo** 2019-03-08 05:02 UTC
Labels: enhancement
